name: Pact-JVM Compatibility Suite

on:
  push:
    branches: [ master, v4.1.x, v4.4.x, v4.5.x ]
  pull_request:
    branches: [ master, v4.1.x, v4.4.x, v4.5.x ]

jobs:
  latest_jdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18
    - name: Build with Gradle
      run: ./gradlew --no-daemon :compatibility-suite:cucumber
